import type { Metadata } from "next";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Providers from "./Redux/Provider";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { cn } from "@/lib/utils";
import Header from "@/components/header";
import { useSelector } from "react-redux";
import { RootState } from "./Redux/slice/interface";

// import Signin from "./signin";

export const metadata: Metadata = {
  title: "Rest-Countries-API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased")}>
        <Providers>
          <div className="">
            <div>
              <Header />
            </div>
            <div>{children}</div>
            <ToastContainer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
