import type { Metadata } from "next";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Providers from "./Redux/Provider";
import { Nunito_Sans } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { cn } from "@/lib/utils";
import Header from "@/components/header";
import { theme } from "./Redux/slice/themeswitcherslice";
import { useSelector } from "react-redux";
import { RootState } from "./Redux/slice/interface";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});
export const metadata: Metadata = {
  title: "Rest-Countries-API",
  description: "Generated by create next app",
};

//console.log("layout:", theme);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(" min-h-screen antialiased")}>
        <Providers>
          <div className="">
            <Header />
            <div className="">{children}</div>
            <ToastContainer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
